language: python
sudo: required
dist: xenial
python: "3.7"
services: mysql
before_install:
  - export DJANGO_SETTINGS_MODULE=louiscailleux.settings
  - export PYTHONPATH="/usr/local/lib/python3.7/dist-packages"

env:
  - DJANGO=2.1.4

install:
  - "pip install -r requirements.txt"

before_script:
  - mysql -u travis -e "CREATE DATABASE travisci"

script:
  - pytest