version: '3.5'

services:
  db:
    image: mariadb
    ports:
      - "3306:3306"
    env_file:
      - ./django/.env
  louiscailleux_backend:
    build:
      context: ./django
      dockerfile: Dockerfile.prod
    environment:
      WAIT_HOSTS: db:3306
    ports:
      - "8000:8000"
    volumes:
      - ./django:/code
    depends_on:
      - db
  louiscailleux_frontend:
    build:
      context: ./react
      dockerfile: Dockerfile.prod
    links:
      - louiscailleux_backend
    volumes:
      - './react:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3000:3000'
    depends_on:
      - louiscailleux_backend