FROM python:3
ENV PYTHONUNBUFFERED 1
ENV HEROKU 1

RUN mkdir /code
WORKDIR /code

COPY requirements.txt /code/
RUN pip install -r requirements.txt

COPY . /code/

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait
RUN chmod +x /wait

RUN python louiscailleux/manage.py collectstatic --noinput

EXPOSE 80

WORKDIR /code/louiscailleux
CMD /wait && python manage.py migrate && gunicorn louiscailleux.wsgi:application --bind 0.0.0.0:$PORT --workers 3