version: '3.5'

services:
  louiscailleux_frontend:
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3000:3000'