# Generated by Django 2.1.7 on 2019-03-13 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            'ALTER TABLE projects_project CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci'
        )
    ]
