# Generated by Django 2.1.7 on 2019-03-13 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_block_language_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='show_title',
            field=models.BooleanField(default=1),
        ),
    ]
