# Generated by Django 2.1.5 on 2019-02-01 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='language_code',
            field=models.CharField(default='en', max_length=3),
        ),
    ]
