# Generated by Django 2.1.7 on 2019-03-12 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_block_language_code'),
    ]

    operations = [
        migrations.RunSQL(
            'ALTER TABLE cms_block CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci'
        )
    ]
