version: '3.5'

services:
  db:
    image: mariadb
    env_file:
      - .env
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - "8080:80"
    volumes:
      - /sessions
    depends_on:
      - db
  louiscailleux_backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      WAIT_HOSTS: db:3306
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - db