version: '3.5'

services:
  db:
    image: mariadb
    env_file:
      - .env
  louiscailleux_backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      WAIT_HOSTS: db:3306
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - db